version: '3.9'
services:
  app:
    image: nam2507/foodrec:foodrec_v1
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/foodrec-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - db
      - redis-server

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foodrec-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - /path/to/database/data:/var/lib/postgresql/data

  redis-server:
    hostname: redis
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
