spring:
  datasource:
    url: ${POSTGRESQL_URI}
    username: ${POSTGRESQL_DATABASE_NAME}
    password: ${POSTGRESQL_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: FoodRec
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.yp2743.me/realms/swp
jwt:
  auth:
    converter:
      resource-id: ${spring.application.name}
      principal-attribute: preferred_username
app:
  cors:
    allowed-origins: http://localhost:5173

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.security: DEBUG