version: '3.9'
services:
  app:
    image: nam2507/foodrec:foodrec_v1
    container_name: foodrec
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOSTNAME: ${SPRING_REDIS_HOSTNAME}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
      SPRING_ELASTICSEARCH_HOSTNAME: ${SPRING_ELASTICSEARCH_HOSTNAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_URL: ${OPENAI_API_URL}
      OPENAI_API_MODEL: ${OPENAI_API_MODEL}
    depends_on:
      - db
      - redis-server
      - elasticsearch

  db:
    image: postgres:15-alpine
    container_name: foodrec_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-server:
    image: redis:latest
    hostname: ${SPRING_REDIS_HOSTNAME}
    container_name: foodrec_redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    hostname: ${SPRING_ELASTICSEARCH_HOSTNAME}
    container_name: foodrec_elasticsearch
    restart: always
    environment:
      - cluster.name=foodrec
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  esdata:

